const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
class ClassList{constructor(el){this.el=el} _set(){return new Set(String(this.el.className||'').split(/\s+/).filter(Boolean))}contains(x){return this._set().has(x)}add(...xs){const s=this._set();xs.forEach(x=>s.add(x));this.el.className=[...s].join(' ')}}
class El{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.className='';this.classList=new ClassList(this);this.textContent='';this.attrs={};this.dataset={}}appendChild(x){this.children.push(x);return x}append(...xs){xs.forEach(x=>this.appendChild(x))}replaceChildren(...xs){this.children=[...xs];this.textContent=''}setAttribute(k,v){this.attrs[k]=String(v)}getAttribute(k){return this.attrs[k]}querySelector(sel){return sel==='.tile-svg'?this.children.find(x=>String(x.className||x.attrs&&x.attrs.class||'').split(/\s+/).includes('tile-svg'))||null:null}querySelectorAll(sel){const out=[];const walk=n=>{(n.children||[]).forEach(c=>{if(sel==='.tile'&&c.classList&&c.classList.contains('tile'))out.push(c);walk(c)})};walk(this);return out}}
const table=new El('div');table.id='tableRoot';global.window=global;global.document={getElementById:id=>id==='tableRoot'?table:null,createElement:t=>new El(t),createElementNS:(ns,t)=>new El(t)};global.MutationObserver=class{constructor(cb){this.cb=cb}observe(){this.observing=true}};
const root=path.join(__dirname,'..');const load=rel=>vm.runInThisContext(fs.readFileSync(path.join(root,rel),'utf8'),{filename:rel});
load('src/game/Tile.js');load('src/ui/renderTiles.js');
const hand=new El('button');hand.className='tile red';hand.textContent='5p';table.appendChild(hand);const honor=new El('span');honor.className='tile';honor.textContent='東';table.appendChild(honor);const back=new El('span');back.className='tile back';back.textContent='■';table.appendChild(back);
load('src/ui/TileFaceBridge.js');
assert.ok(global.Sanma.RenderTiles&&global.Sanma.TileFaceBridge);assert.ok(hand.querySelector('.tile-svg'),'suited tile should become SVG');assert.ok(honor.querySelector('.tile-svg'),'honor tile should become SVG');assert.strictEqual(back.querySelector('.tile-svg'),null,'hidden back must stay hidden');assert.strictEqual(hand.getAttribute('aria-label'),'赤五筒');assert.strictEqual(honor.getAttribute('aria-label'),'東');assert.ok(hand.classList.contains('tile-red'));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.ok(html.indexOf('src/ui/renderTiles.js')<html.indexOf('src/main.js'),'renderer must load before main');assert.ok(html.indexOf('src/main.js')<html.indexOf('src/ui/TileFaceBridge.js'),'bridge must load after main');assert.ok(html.includes('src/styles/tile-faces.css'));
console.log('tile-face-bootstrap: ok');
