import { describe, expect, it } from 'vitest';
import type { LoopDeckPack, ModuleInfo, Question } from '../src/core/models';
import { mergeLoopDeckPacks, mergeLoopDeckPacksIntoExisting } from '../src/packs/packMerger';
import { validatePack } from '../src/packs/packValidator';
function inputQuestion(id: string, moduleId: string, prompt: string, answer = `${prompt} answer`): Question { return { id, moduleId, type: 'input', prompt, answer }; }
function moduleInfo(id: string, title: string, questionIds: string[], overrides: Partial<ModuleInfo> = {}): ModuleInfo { return { id, folderId: 'folder-1', title, subject: '英語', description: `${title} description`, tags: [title], questionIds, ...overrides }; }
function pack(overrides: Partial<LoopDeckPack> = {}): LoopDeckPack { return { packVersion: 1, packId: 'shared-pack', title: 'Existing pack', description: 'Existing description', folders: [{ id: 'folder-1', title: 'Existing folder' }], modules: [moduleInfo('module-1','Existing module',['q-1'])], questions: [inputQuestion('q-1','module-1','existing prompt')], ...overrides }; }
describe('mergeLoopDeckPacks', () => {
  it('merges same packId and lets incoming metadata win', () => { const result = mergeLoopDeckPacks(pack({title:'Old'}), pack({title:'New',description:'New desc'})); expect(result.pack.title).toBe('New'); expect(result.pack.description).toBe('New desc'); });
  it('merges modules and adds questions', () => { const incoming = pack({ modules:[moduleInfo('module-1','New module',['q-2'],{subject:'数学'})], questions:[inputQuestion('q-2','module-1','incoming')] }); const result = mergeLoopDeckPacks(pack(), incoming); expect(result.pack.modules[0].questionIds).toEqual(['q-1','q-2']); expect(result.report.addedQuestions).toBe(1); expect(result.report.mergedModules).toBe(1); });
  it('renames conflicting changed questions and remaps module ids', () => { const existing = pack({questions:[inputQuestion('q-1','module-1','old')]}); const incoming = pack({modules:[moduleInfo('module-1','Incoming',['q-1'])],questions:[inputQuestion('q-1','module-1','new')]}); const result = mergeLoopDeckPacks(existing,incoming); expect(result.pack.questions.find(q=>q.id==='q-1')?.prompt).toBe('old'); expect(result.pack.questions.find(q=>q.id==='q-1__merge_1')?.prompt).toBe('new'); expect(result.pack.modules[0].questionIds).toEqual(['q-1','q-1__merge_1']); });
  it('skips identical conflicts', () => { const shared = inputQuestion('q-1','module-1','same'); const result = mergeLoopDeckPacks(pack({questions:[shared]}), pack({questions:[shared]})); expect(result.report.skippedIdenticalQuestions).toBe(1); expect(result.pack.questions.filter(q=>q.id==='q-1')).toHaveLength(1); });
  it('validates a merged pack', () => { const result = mergeLoopDeckPacks(pack(), pack({modules:[moduleInfo('module-1','Updated',['q-1','q-2'])],questions:[inputQuestion('q-1','module-1','updated'),inputQuestion('q-2','module-1','new')]})); expect(validatePack(result.pack).ok).toBe(true); });
  it('can merge a different-pack addon into an existing module', () => { const existing = pack({packId:'built-in-final',modules:[moduleInfo('leap_final','LEAP 201〜300',['leap_final-201'])],questions:[inputQuestion('leap_final-201','leap_final','ability','能力')]}); const incoming = pack({packId:'addon',modules:[moduleInfo('leap_final','LEAP 301〜400',['leap_final-301'])],questions:[inputQuestion('leap_final-301','leap_final','modern','現代の')]}); const result = mergeLoopDeckPacksIntoExisting(existing,incoming); expect(result.pack.packId).toBe('built-in-final'); expect(result.pack.modules[0].questionIds).toEqual(['leap_final-201','leap_final-301']); });
});
