import { describe, expect, it } from 'vitest';
import type { LoopDeckPack, ModuleInfo, Question } from '../src/core/models';
import { getActivePacks, getQuestionById, getQuestionsForModule, getModuleById, resolveActivePacks } from '../src/packs/packResolver';
function inputQuestion(id: string, moduleId: string, prompt: string): Question { return { id, moduleId, type: 'input', prompt, answer: `${prompt} answer` }; }
function moduleInfo(id: string, title: string, questionIds: string[]): ModuleInfo { return { id, folderId: 'term1_midterm', title, subject: '英語', description: `${title} description`, tags: [title], questionIds }; }
function pack(packId: string, title: string, modules: ModuleInfo[], questions: Question[]): LoopDeckPack { return { packVersion: 1, packId, title, folders: [{ id: 'term1_midterm', title: '一学期中間テスト' }], modules, questions }; }
describe('packResolver duplicate ID resolution', () => {
  it('uses imported module/question data when it overrides a built-in module', () => { const builtin = pack('loopdeck-builtin-v1','Built-in',[moduleInfo('leap','LEAP old',['leap-001'])],[inputQuestion('leap-001','leap','old prompt')]); const imported = pack('user-leap-update','Imported LEAP',[moduleInfo('leap','LEAP new',['leap-001'])],[inputQuestion('leap-001','leap','new prompt')]); const view = resolveActivePacks([builtin, imported]); expect(getModuleById(view,'leap')?.title).toBe('LEAP new'); expect(getQuestionsForModule(view,'leap')[0]?.prompt).toBe('new prompt'); });
  it('treats a later pack with the same packId as a full replacement', () => { const v1 = pack('custom-leap','v1',[moduleInfo('m','old',['old'])],[inputQuestion('old','m','old content')]); const v2 = pack('custom-leap','v2',[moduleInfo('m','new',['new'])],[inputQuestion('new','m','new content')]); const view = resolveActivePacks([v1,v2]); expect(getActivePacks(view)).toHaveLength(1); expect(getQuestionsForModule(view,'m')[0]?.prompt).toBe('new content'); expect(getQuestionById(view,'old')).toBeUndefined(); });
  it('lets imported questions win when question IDs collide', () => { const builtin = pack('b','B',[moduleInfo('bm','B',['shared'])],[inputQuestion('shared','bm','old')]); const imported = pack('i','I',[moduleInfo('im','I',['shared'])],[inputQuestion('shared','im','new')]); expect(getQuestionById(resolveActivePacks([builtin, imported]),'shared')?.prompt).toBe('new'); });
});
