const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
class El{constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.children=[];this.dataset={};this.className='';this.textContent='';this.disabled=false;this.type='';this.value='';this.checked=false;this._html='';this.style={};this.options=[];}appendChild(x){this.children.push(x);if(this.tagName==='SELECT')this.options.push(x);return x}append(...xs){xs.forEach(x=>this.appendChild(x))}remove(){this.removed=true}set innerHTML(v){this._html=String(v);this.children=[]}get innerHTML(){return this._html}querySelectorAll(){return []}querySelector(){return null}showModal(){this.open=true}close(){this.open=false}click(){if(this.onclick)this.onclick()}addEventListener(type,fn){this['on'+type]=fn}setAttribute(k,v){this[k]=String(v)}}
const ids=['tableRoot','actionRoot','logRoot','statusLine','newGameButton','settingsButton','recordsButton','replayButton','debugButton','settingsDialog','settingsRoot','settingsTransferRoot','saveSettingsButton','recordsDialog','recordsRoot','replayDialog','replayRoot','replayRecordSelect','closeReplayButton','debugDialog','seedInput','applySeedButton','resetStorageButton','debugRoot'];
const nodes=Object.fromEntries(ids.map(id=>[id,new El(id.includes('Dialog')?'dialog':id.includes('Select')?'select':'div',id)]));
global.window=global;global.document={documentElement:new El('html'),body:new El('body'),getElementById:id=>nodes[id]||null,createElement:tag=>new El(tag),querySelectorAll:()=>[]};
global.localStorage={_m:new Map(),getItem(k){return this._m.has(k)?this._m.get(k):null},setItem(k,v){this._m.set(k,String(v))},removeItem(k){this._m.delete(k)},key(i){return [...this._m.keys()][i]||null},get length(){return this._m.size}};global.URL={createObjectURL(){return'blob:x'},revokeObjectURL(){}};global.Blob=class{};global.alert=()=>{};global.confirm=()=>true;global.prompt=()=>null;global.navigator={clipboard:{writeText:async()=>{}}};global.location={reload(){}};
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),scripts=[...html.matchAll(/<script\s+src="([^"]+)"/g)].map(m=>m[1]);
for(const rel of scripts){const f=path.join(root,rel);vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:rel});}
assert.strictEqual(document.documentElement.dataset.mahjongReady,'true');assert.ok(global.__mahjongApp&&global.__mahjongApp.engine);assert.ok(nodes.tableRoot.children.length>=4,'table should render three players and center');
const state=global.__mahjongApp.state;assert.strictEqual(state.players.length,3);assert.ok(state.wall&&Number.isInteger(state.wall.remainingCount));assert.ok(Array.isArray(state.humanActions));assert.ok(state.match);assert.ok(state.players.find(p=>p.isHuman).hand.length>0);state.players.filter(p=>!p.isHuman).forEach(p=>assert.strictEqual(p.hand.length,0,'CPU hand leaked'));assert.ok(Sanma.ReplayViewer&&Sanma.RecordsDashboard&&Sanma.SettingsExportImport);
console.log(`snapshot-browser-smoke: ok (${scripts.length} scripts, ${state.phase})`);
