(function boot(global){
const S=global.Sanma, $=id=>document.getElementById(id); let engine=null,lastState=null,settings=S.SettingsStorage.loadSettings(),committed=new Set();
const table=$('tableRoot'),actions=$('actionRoot'),logs=$('logRoot'),status=$('statusLine');
function tileEl(t,clickable){const e=document.createElement(clickable?'button':'span');e.className='tile'+(t&&t.isRed?' red':'')+(t?'':' back');e.textContent=t?(t.label||`${t.rank||''}${t.suit||''}`):'■';if(clickable&&t)e.onclick=()=>engine.discardHumanTile(t.instanceId);return e}
function tiles(root,list,clickable){root.innerHTML='';(list||[]).forEach(t=>root.appendChild(tileEl(t,clickable)))}
function renderPlayer(p,state){const box=document.createElement('article');box.className='player'+(state.turnIndex===p.id?' active':'');box.dataset.seat=p.id;const head=document.createElement('div');head.className='player-head';head.innerHTML=`<strong>${escapeHtml(p.name)} ${p.hasRiichi?'🀄立直':''}</strong><span class="points">${p.points.toLocaleString()}点</span>`;box.appendChild(head);const meta=document.createElement('div');meta.className='meta';meta.textContent=`${p.seatWind||''} / 北抜き ${p.kitaTiles.length} / 手牌 ${p.isHuman?p.hand.length:p.concealedCount}枚`;box.appendChild(meta);const melds=document.createElement('div');melds.className='melds';(p.melds||[]).forEach(m=>{const mbox=document.createElement('span');mbox.className='meld';(m.tiles||[]).forEach(t=>mbox.appendChild(tileEl(t,false)));melds.appendChild(mbox)});box.appendChild(melds);const disc=document.createElement('div');disc.className='discards';tiles(disc,p.discards,false);box.appendChild(disc);if(p.isHuman){const h=document.createElement('div');h.className='tiles hand';tiles(h,p.hand,state.phase==='human-discard'||state.phase==='caller-discard');box.appendChild(h)}else{const h=document.createElement('div');h.className='tiles';for(let i=0;i<Math.min(p.concealedCount,14);i++)h.appendChild(tileEl(null,false));box.appendChild(h)}return box}
function render(state){lastState=state;table.innerHTML='';state.players.forEach(p=>table.appendChild(renderPlayer(p,state)));const c=document.createElement('section');c.className='center';const dora=(state.wall.doraIndicators||[]).map(t=>t.label).join(' ');c.innerHTML=`<strong>${escapeHtml(state.round.label||'')} ${state.round.honba||0}本場</strong><div>${state.wall.remainingCount}枚 / ドラ表示 ${escapeHtml(dora||'-')}</div><div>供託 ${state.round.riichiSticks||0}</div><div class="muted">seed: ${escapeHtml(state.seed)}</div>`;table.appendChild(c);status.textContent=`${state.phase} ・ ${state.match&&state.match.matchEnded?'対局終了':'対局中'}`;renderActions(state);logs.innerHTML=(state.logs||[]).slice(0,30).map(x=>`<p>${escapeHtml(x)}</p>`).join('');persist(state);document.documentElement.dataset.mahjongReady='true'}
function button(label,fn,disabled=false,cls=''){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.className=cls;b.onclick=fn;actions.appendChild(b)}
function renderActions(state){actions.innerHTML='';if(state.callWindow){const label=document.createElement('span');label.className='call-label';label.textContent=`${state.callWindow.tile&&state.callWindow.tile.label||''} に反応`;actions.appendChild(label);state.callWindow.actions.filter(a=>a.enabled).forEach(a=>{const opts=a.options&&a.options.length?a.options:[null];opts.forEach((o,i)=>button(o&&o.label?`${a.label} ${o.label}`:a.label,()=>a.id==='ron'?engine.claimHumanRon():engine.claimHumanCall(a.id,i),false,'primary'))});button('見送る',()=>engine.skipHumanCall());return}if(state.phase==='human-discard'||state.phase==='caller-discard'){const by=id=>state.humanActions.find(a=>a.id===id);const ts=by('tsumo');if(ts&&ts.enabled)button('ツモ',()=>engine.claimHumanTsumo(),false,'primary');const ri=by('riichi');if(ri&&ri.enabled)button('リーチ',()=>engine.declareHumanRiichi());const ki=by('kita');if(ki&&ki.enabled){const hp=state.players.find(p=>p.isHuman);(hp&&hp.hand||[]).filter(t=>t.suit==='z'&&t.rank===4).forEach(t=>button('北抜き',()=>engine.requestHumanKita(t.instanceId)))}const ka=by('kan');if(ka&&ka.enabled)(ka.options&&ka.options.length?ka.options:[{}]).forEach((o,i)=>button(`カン${o.label?' '+o.label:''}`,()=>engine.requestHumanKan(i)));const hint=document.createElement('span');hint.className='muted';hint.textContent='手牌をクリックして打牌';actions.appendChild(hint)}if(state.phase==='win-ended'||state.phase==='round-ended'){if(state.match&&state.match.matchEnded)button('新しい対局',()=>newGame());else button('次局へ',()=>engine.startNextRound(),false,'primary')}if(!actions.children.length){const s=document.createElement('span');s.className='muted';s.textContent='CPU思考中…';actions.appendChild(s)}}
function persist(state){if(!state.gameRecord||!S.GameRecordStorage)return;try{if(state.phase==='win-ended'||state.phase==='round-ended')S.GameRecordStorage.saveRecord(state.gameRecord);if(state.match&&state.match.matchEnded&&!committed.has(state.gameRecord.id)){S.GameRecordStorage.commitRecord(state.gameRecord);committed.add(state.gameRecord.id)}}catch(e){console.warn(e)}}
function newGame(seed){try{engine=new S.GameEngine({ruleConfig:settings,seed:seed||`sanma-${Date.now()}`,onChange:render});global.__mahjongApp={get engine(){return engine},get state(){return lastState},newGame};render(engine.getState())}catch(e){status.textContent=`起動失敗: ${e.message}`;console.error(e)}}
function renderSettings(){const root=$('settingsRoot');root.innerHTML='';S.RuleConfig.normalSettings.forEach(spec=>{const l=document.createElement('label');l.className='setting';const name=document.createElement('span');name.textContent=spec.label;l.appendChild(name);let input;if(spec.type==='select'){input=document.createElement('select');spec.options.forEach(o=>{const op=document.createElement('option');op.value=o.value;op.textContent=o.label;op.selected=settings[spec.key]===o.value;input.appendChild(op)})}else{input=document.createElement('input');input.type='checkbox';input.checked=Boolean(settings[spec.key])}input.dataset.key=spec.key;l.appendChild(input);root.appendChild(l)})}
function saveSettings(){const next=Object.assign({},settings);$('settingsRoot').querySelectorAll('[data-key]').forEach(i=>next[i.dataset.key]=i.type==='checkbox'?i.checked:i.value);settings=S.RuleConfig.createRuleConfig(next);S.SettingsStorage.saveSettings(settings);$('settingsDialog').close();newGame()}
function recordTitle(r){const ps=(r.players||[]).map((p,i)=>`${p.name||`P${i+1}`}${r.finalPoints&&Number.isFinite(Number(r.finalPoints[i]))?` ${Number(r.finalPoints[i]).toLocaleString()}`:''}`).join(' / ');return `${r.completedAt?'完了':'進行中'} ${ps}`}
function renderRecords(){const root=$('recordsRoot'),records=S.GameRecordStorage.loadRecords(),stats=S.GameRecordStorage.loadStats();root.innerHTML=`<div class="stats"><span>対局 ${stats.gamesPlayed||0}</span><span>和了 ${stats.wins||0}</span><span>放銃/敗北 ${stats.losses||0}</span><span>役満 ${stats.yakumanCount||0}</span></div><div class="row"><button id="importRecordButton">牌譜JSONをインポート</button></div>`;$('importRecordButton').onclick=()=>{const text=prompt('牌譜JSONを貼り付けてください');if(text!=null){const r=S.GameRecordStorage.importRecord(text);alert(r.reason);renderRecords()}};records.forEach(r=>{const box=document.createElement('article');box.className='record';const h=document.createElement('header');h.innerHTML=`<strong>${escapeHtml(recordTitle(r))}</strong><span>${escapeHtml(r.createdAt||'')}</span>`;box.appendChild(h);const p=document.createElement('p');p.textContent=`${(r.rounds||[]).length}局 / id ${r.id}`;box.appendChild(p);const row=document.createElement('div');row.className='row';const view=document.createElement('button');view.textContent='内容';view.onclick=()=>{let pre=box.querySelector('pre');if(pre){pre.remove();return}pre=document.createElement('pre');pre.textContent=(r.rounds||[]).map((round,i)=>`#${i+1} ${round.roundLabel||''}\n${(round.events||[]).map(e=>`${e.index||''} ${e.type}`).join('\n')}\n結果: ${JSON.stringify(round.result||null,null,2)}`).join('\n\n');box.appendChild(pre)};row.appendChild(view);const exp=document.createElement('button');exp.textContent='JSON書き出し';exp.onclick=()=>download(`${r.id}.json`,JSON.stringify(r,null,2));row.appendChild(exp);const del=document.createElement('button');del.textContent='削除';del.onclick=()=>{if(confirm('この牌譜を削除しますか？')){S.GameRecordStorage.deleteRecord(r.id);renderRecords()}};row.appendChild(del);box.appendChild(row);root.appendChild(box)})}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function debug(){const inv=engine?S.TileLedger.inspect(engine,engine.ruleConfig):null;$('debugRoot').textContent=JSON.stringify({state:lastState,ledger:inv,storage:S.GameRecordStorage.getDiagnostics(),settings:S.SettingsStorage.getDiagnostics()},null,2)}
function escapeHtml(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('newGameButton').onclick=()=>newGame();$('settingsButton').onclick=()=>{renderSettings();$('settingsDialog').showModal()};$('saveSettingsButton').onclick=saveSettings;$('recordsButton').onclick=()=>{renderRecords();$('recordsDialog').showModal()};$('debugButton').onclick=()=>{debug();$('debugDialog').showModal()};$('applySeedButton').onclick=()=>{$('debugDialog').close();newGame($('seedInput').value.trim()||undefined)};$('resetStorageButton').onclick=()=>{if(confirm('保存設定・牌譜・成績を全て削除しますか？')){S.SettingsStorage.resetAllStorage();settings=S.SettingsStorage.loadSettings();alert('削除しました')}};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
newGame();
})(window);
