(function attachRecordsDashboard(global){
const S=global.Sanma,$=id=>document.getElementById(id),root=$('recordsRoot'),dialog=$('recordsDialog');
const E=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function btn(text,fn,cls=''){const b=E('button',cls,text);b.type='button';b.onclick=fn;return b;}
function human(record){const p=(record.players||[]).find(x=>x&&x.isHuman);return p&&Number.isInteger(p.id)?p.id:0;}
function recordById(records,id){return records.find(r=>String(r.id)===String(id))||null;}
function highest(entry){const r=entry.highestHand;if(!r||!r.score)return '最高打点: 集計不可';if(r.score.isYakuman)return `最高打点: ${r.score.limitName||'役満'}`;return `最高打点: ${[r.score.limitName,Number(r.score.han)?`${r.score.han}翻`:null,Number(r.score.fu)?`${r.score.fu}符`:null].filter(Boolean).join(' ')||'集計不可'}`;}
function metricGrid(items){const g=E('div','records-metrics');items.forEach(([k,v])=>{const x=E('div','records-metric');x.append(E('span','',k),E('strong','',v));g.append(x)});return g;}
function statsView(records){const stats=S.AdvancedStats.calculate(records),box=E('section','records-pane');box.append(E('h3','','対局成績'),metricGrid([['対局数',S.AdvancedStats.display(stats.match.gamesPlayed)],['1位回数',S.AdvancedStats.display(stats.match.firstPlaceCount)],['平均順位',S.AdvancedStats.display(stats.match.averageRank,'位')],['平均最終点',S.AdvancedStats.display(stats.match.averageFinalPoints,'点')],['最高最終点',S.AdvancedStats.display(stats.match.bestFinalPoints,'点')]]),E('h3','','局成績'),metricGrid([['和了',S.AdvancedStats.display(stats.hand.wins)],['敗北',S.AdvancedStats.display(stats.hand.losses)],['放銃',S.AdvancedStats.display(stats.hand.dealInCount)],['ツモ和了',S.AdvancedStats.display(stats.hand.tsumoWinCount)],['ロン和了',S.AdvancedStats.display(stats.hand.ronWinCount)],['最高獲得点',S.AdvancedStats.display(stats.hand.highestScore,'点')],['役満',S.AdvancedStats.display(stats.hand.yakumanCount)]]));
const y=E('div','records-yaku');y.append(E('strong','','役頻度'));const pairs=Object.entries(stats.yaku.frequency||{}).sort((a,b)=>b[1]-a[1]);y.append(E('div','record-summary',pairs.length?pairs.map(([n,c])=>`${n} ${c}回`).join(' / '):'役データなし'));box.append(y);return box;}
function render(){
 const records=S.GameRecordStorage.loadRecords(),entries=S.GameRecordStorage.loadIndex(records);root.innerHTML='';let replay=null,selected=entries[0]?entries[0].id:null;
 const tabs=E('div','records-tabs'),body=E('div','records-body'),status=E('div','records-status');
 function stopReplay(){if(replay&&replay.stop)replay.stop();replay=null;}
 function showList(){stopReplay();body.innerHTML='';const filters=E('div','records-filters'),q=E('input'),outcome=E('select'),tag=E('select'),list=E('div','records-list');q.type='search';q.placeholder='日付・順位・タグで検索';[['all','全結果'],['win','和了局あり'],['loss','敗北あり']].forEach(([v,t])=>{const o=E('option','',t);o.value=v;outcome.append(o)});[['all','全タグ'],['yakuman','役満'],['highScore','高打点']].forEach(([v,t])=>{const o=E('option','',t);o.value=v;tag.append(o)});filters.append(q,outcome,tag);function draw(){list.innerHTML='';const filtered=S.RecordIndex.filter(entries,{query:q.value,outcome:outcome.value,tag:tag.value});if(!filtered.length){list.append(E('div','record-empty','条件に一致する牌譜はありません。'));return;}filtered.forEach(entry=>{const r=recordById(records,entry.id),card=E('article','records-card'),summary=E('div','records-summary'),actions=E('div','records-actions');summary.append(E('strong','',entry.summary),E('span','',entry.createdAt||'日時不明'),E('span','records-tags',entry.tags.join(' / ')||'タグなし'),E('span','',highest(entry)),E('span','','サイズ '+entry.sizeBytes.toLocaleString()+' bytes'));actions.append(btn('詳細',()=>{selected=entry.id;const pre=card.querySelector('pre')||E('pre','records-detail');pre.textContent=JSON.stringify({rounds:(r.rounds||[]).length,finalPoints:r.finalPoints,finalRankings:r.finalRankings,matchEndReason:r.matchEndReason},null,2);if(!pre.parentNode)card.append(pre)}),btn('再生',()=>showReplay(entry.id)),btn('JSON',()=>showJson(entry.id)),btn('削除',()=>{if(global.confirm&&!global.confirm('この牌譜を削除しますか？'))return;if(!S.GameRecordStorage.deleteRecord(entry.id))throw new Error('牌譜を削除できませんでした。');render();},'danger'));card.append(summary,actions);list.append(card)});}q.oninput=draw;outcome.onchange=draw;tag.onchange=draw;body.append(filters,list);draw();}
 function showReplay(id){stopReplay();selected=id;body.innerHTML='';const r=recordById(records,id);if(!r){body.append(E('div','record-empty','再生する牌譜がありません。'));return;}replay=S.ReplayViewer.mount(body,r);}
 function showJson(id){stopReplay();selected=id;body.innerHTML='';const r=recordById(records,id),area=E('textarea','records-json');area.value=r?JSON.stringify(r,null,2):'';const actions=E('div','records-actions');actions.append(btn('コピー',()=>{if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(area.value).then(()=>status.textContent='コピーしました。').catch(()=>status.textContent='手動でコピーしてください。');else status.textContent='手動でコピーしてください。';}),btn('一覧へ',showList));body.append(actions,area);}
 function showImport(){stopReplay();body.innerHTML='';const area=E('textarea','records-json');area.placeholder='インポートする牌譜JSON';body.append(area,btn('インポート',()=>{const engine=global.__mahjongApp&&global.__mahjongApp.engine,result=S.GameRecordStorage.importRecord(area.value,{activeRecordId:engine&&engine.gameRecord?engine.gameRecord.id:null});status.textContent=result.reason;if(result.ok)render();}));}
 tabs.append(btn('牌譜一覧',showList),btn('選択を再生',()=>showReplay(selected)),btn('成績',()=>{stopReplay();body.innerHTML='';body.append(statsView(records));}),btn('インポート',showImport),btn('牌譜リセット',()=>{if(global.confirm&&!global.confirm('保存済み牌譜をすべて削除しますか？'))return;if(!S.GameRecordStorage.resetRecords())throw new Error('牌譜をリセットできませんでした。');render();},'danger'),btn('成績リセット',()=>{if(global.confirm&&!global.confirm('成績集計をリセットしますか？'))return;if(!S.GameRecordStorage.resetStats())throw new Error('成績をリセットできませんでした。');render();},'danger'));
 root.append(tabs,body,status);showList();
}
$('recordsButton').onclick=()=>{render();dialog.showModal();};S.RecordsDashboard={render};
})(window);
