(function(global){
const S=global.Sanma=global.Sanma||{}, clone=v=>JSON.parse(JSON.stringify(v));
const zones=n=>Array.from({length:Math.max(n,3)},()=>[]), label=t=>typeof t==='string'?t:(t&&(t.label||t.baseId))||'?';
function same(a,b){return a&&b&&a.instanceId&&b.instanceId?a.instanceId===b.instanceId:label(a)===label(b)}
function rm(list,t){for(let i=list.length-1;i>=0;i--)if(same(list[i],t)){list.splice(i,1);return true}return false}
function base(record,round){const n=Math.max((record.players||[]).length,3);return{hands:zones(n),discards:zones(n),melds:zones(n),kita:zones(n),points:Array.isArray(round.startingPoints)?round.startingPoints.slice():(record.players||[]).map(p=>Number(p.initialPoints)||0),diagnostics:[]}}
function pz(v,k,i){return Number.isInteger(i)&&v[k]&&Array.isArray(v[k][i])?v[k][i]:null}
function points(v,changes){(changes||[]).forEach(c=>{if(Number.isInteger(c.playerIndex)&&Number.isFinite(Number(c.after)))v.points[c.playerIndex]=Number(c.after)})}
function apply(v,e){if(!e)return v;const d=e.data||{},i=Number(d.playerIndex),hand=pz(v,'hands',i);
 if(e.type==='deal'&&Array.isArray(d.hands))d.hands.forEach(x=>{if(x&&pz(v,'hands',x.playerIndex)&&Array.isArray(x.tiles))v.hands[x.playerIndex]=clone(x.tiles)});
 else if(e.type==='draw'&&hand&&d.tile)hand.push(d.tile);
 else if(e.type==='discard'&&hand&&pz(v,'discards',i)&&d.tile){if(!rm(hand,d.tile))v.diagnostics.push('discard mismatch '+label(d.tile));v.discards[i].push(d.tile)}
 else if(e.type==='call'&&d.action!=='skip'&&hand&&pz(v,'melds',i)){const mt=(d.tiles||[]).slice();if(d.calledTile&&!mt.some(t=>same(t,d.calledTile)))mt.push(d.calledTile);let ts=(d.consumedTiles||[]).slice();if(!ts.length){ts=mt.slice();if(d.calledTile){const j=ts.findIndex(t=>same(t,d.calledTile));if(j>=0)ts.splice(j,1)}}ts.forEach(t=>rm(hand,t));v.melds[i].push({type:d.action||'call',tiles:mt,fromPlayerIndex:d.fromPlayerIndex,open:true});const src=pz(v,'discards',Number(d.fromPlayerIndex));if(src&&src.length){if(d.calledTile)rm(src,d.calledTile);else src.pop()}}
 else if(e.type==='kita'&&hand&&pz(v,'kita',i)&&d.tile){rm(hand,d.tile);v.kita[i].push(d.tile)}
 else if(e.type==='kan'&&hand&&pz(v,'melds',i)){const kind=d.kanType||'kan',ids=(d.consumedTileInstanceIds||[]).map(String),tiles=(d.tiles||[]).slice();if(ids.length){ids.forEach(id=>{const j=hand.findIndex(t=>t&&String(t.instanceId)===id);if(j>=0)hand.splice(j,1);else v.diagnostics.push('kan consume mismatch '+id)})}else (d.consumedTiles||tiles).forEach(t=>rm(hand,t));const meld={type:kind,kanType:kind,tiles,fromPlayerIndex:d.fromPlayerIndex,open:kind!=='ankan'};if(kind==='kakan'&&Number.isInteger(Number(d.meldIndex))&&v.melds[i][Number(d.meldIndex)]){v.melds[i][Number(d.meldIndex)]=Object.assign({},v.melds[i][Number(d.meldIndex)],meld)}else v.melds[i].push(meld);if(kind==='minkan'){const src=pz(v,'discards',Number(d.fromPlayerIndex));if(src&&src.length){if(d.calledTile)rm(src,d.calledTile);else src.pop()}}}
 else if(e.type==='riichi')points(v,d.changes||d.pointChanges);
 else if(e.type==='score_settlement')points(v,d.changes||d.pointChanges||(d.result&&d.result.changes)||(d.result&&d.result.pointChanges));
 else if(e.type==='win'||e.type==='double_ron')points(v,d.changes||d.pointChanges);
 else if(e.type==='round_result'&&Array.isArray(d.finalPoints))v.points=d.finalPoints.slice();return v}
function rebuild(st){const r=st.record.rounds[st.roundIndex],v=base(st.record,r);(r.events||[]).slice(0,st.eventIndex).forEach(e=>apply(v,e));st.view=v;st.diagnostics=v.diagnostics.slice();st.partial=!(r.events||[]).some(e=>e&&e.type==='deal')||v.diagnostics.length>0;return st}
function create(record,roundIndex=0){const r=S.GameRecord.normalize(record),idx=Math.max(0,Math.min(Number(roundIndex)||0,r.rounds.length-1));return rebuild({record:r,recordId:r.id,roundIndex:idx,eventIndex:0,isPlaying:false,speedMs:700,view:{},partial:false})}
function stepForward(st){const e=st.record.rounds[st.roundIndex].events||[];st.eventIndex=Math.min(e.length,st.eventIndex+1);return rebuild(st)}
function stepBack(st){st.eventIndex=Math.max(0,st.eventIndex-1);return rebuild(st)}
function jumpToStart(st){st.eventIndex=0;return rebuild(st)}
function jumpToEnd(st){st.eventIndex=(st.record.rounds[st.roundIndex].events||[]).length;return rebuild(st)}
function setRound(st,i){st.roundIndex=Math.max(0,Math.min(Number(i)||0,st.record.rounds.length-1));st.eventIndex=0;return rebuild(st)}
function eventText(e){if(!e)return '開始';const d=e.data||{};if(e.type==='score_settlement')return `${e.index||''} 点棒精算`.trim();return `${e.index||''} ${e.type}${d.tile?' '+label(d.tile):''}${d.action?' / '+d.action:''}`.trim()}
function E(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function replayTile(x){const n=E('span','replay-tile'),t=x&&typeof x==='object'&&!Array.isArray(x)?x:null;if(t&&t.suit&&Number.isFinite(Number(t.rank))&&S.RenderTiles&&typeof S.RenderTiles.createTileGraphic==='function'){n.append(S.RenderTiles.createTileGraphic(t));if(S.TileUtil&&S.TileUtil.getTileAriaLabel)n.setAttribute('aria-label',S.TileUtil.getTileAriaLabel(t));if(t.isRed)n.className+=' tile-red';}else n.textContent=label(x);return n}
function zone(title,items){const z=E('div','replay-zone'),row=E('div','replay-row');z.append(E('strong','',title),row);(items||[]).forEach(x=>{if(x&&Array.isArray(x.tiles)){const meld=E('span','replay-meld');x.tiles.forEach(t=>meld.append(replayTile(t)));row.append(meld)}else row.append(replayTile(x))});return z}
function mount(root,record){const st=create(record,0);let timer=null;function stop(){st.isPlaying=false;if(timer)global.clearInterval(timer);timer=null}function draw(){const r=st.record.rounds[st.roundIndex],cur=r.events[st.eventIndex-1];root.innerHTML='';const h=E('div','replay-head'),sel=E('select','');st.record.rounds.forEach((x,i)=>{const o=E('option','',x.roundLabel||`局${i+1}`);o.value=i;o.selected=i===st.roundIndex;sel.append(o)});sel.onchange=()=>{stop();setRound(st,sel.value);draw()};h.append(E('strong','',`${r.roundLabel||''} ${st.eventIndex}/${r.events.length}`),sel);const c=E('div','replay-controls');[['先頭',()=>jumpToStart(st)],['戻る',()=>stepBack(st)],['進む',()=>stepForward(st)],['末尾',()=>jumpToEnd(st)]].forEach(([t,f])=>{const b=E('button','',t);b.onclick=()=>{stop();f();draw()};c.append(b)});const play=E('button','',st.isPlaying?'停止':'自動再生');play.onclick=()=>{if(st.isPlaying){stop();draw();return}st.isPlaying=true;timer=global.setInterval(()=>{if(st.eventIndex>=r.events.length){stop();draw()}else{stepForward(st);draw()}},st.speedMs);draw()};c.append(play);const b=E('div','replay-board');st.view.hands.forEach((hand,i)=>{const p=st.record.players[i]||{name:`P${i+1}`},a=E('section','replay-player');a.append(E('h4','',`${p.name} / ${(st.view.points[i]||0).toLocaleString()}点`),zone('手牌',hand),zone('河',st.view.discards[i]),zone('副露',st.view.melds[i]),zone('抜き北',st.view.kita[i]));b.append(a)});root.append(h,c,b,E('div','replay-event',eventText(cur)));if(st.partial)root.append(E('div','replay-warning','古い/欠損牌譜のため一部表示を省略しています'))}draw();return{state:st,stop,draw}}
S.ReplayViewer={create,applyEvent:apply,rebuild,stepForward,stepBack,jumpToStart,jumpToEnd,setRound,eventText,tileLabel:label,sameTile:same,mount,clone};
})(window);
