(function attachCpuRiskAnalysis(global){
  const Sanma=global.Sanma=global.Sanma||{},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const players=s=>Array.isArray(s&&s.players)?s.players:[];
  const riichi=p=>Boolean(p&&(p.hasRiichi||(p.riichi&&(p.riichi.declared||p.riichi.pending))));
  const dealer=(s,i)=>Boolean(s&&s.round&&s.round.dealerIndex===i);
  const left=s=>s&&s.wall&&typeof s.wall.remainingCount==='function'?s.wall.remainingCount():(Number.isFinite(s&&s.wallRemaining)?Number(s.wallRemaining):70);
  const id=(s,r)=>Sanma.TileUtil&&Sanma.TileUtil.baseId?Sanma.TileUtil.baseId(s,r):`${r}${s}`;
  const river=p=>new Set((p&&p.discards||[]).filter(Boolean).map(t=>t.baseId));
  function threats(state,me){const rem=left(state);return players(state).map((p,i)=>{if(!p||i===me)return null;const open=(p.melds||[]).filter(m=>m&&m.open).length,kita=(p.kitaTiles||[]).length,r=riichi(p);let level=r?70:8;level+=open>=2?24:open===1?12:0;level+=dealer(state,i)?8:0;level+=Math.min(16,kita*4);if(rem<=18)level+=8;if(rem<=8)level+=8;return{playerIndex:i,playerName:p.name||`P${i}`,riichi:r,dealer:dealer(state,i),openMeldCount:open,kitaCount:kita,discardCount:(p.discards||[]).length,threatLevel:clamp(level,0,100)};}).filter(Boolean);}
  function suji(p,t){if(!t||!['m','p','s'].includes(t.suit))return false;const d=river(p),r=t.rank,s=t.suit;if(r<=3&&d.has(id(s,r+3)))return true;if(r>=7&&d.has(id(s,r-3)))return true;return r>=4&&r<=6&&(d.has(id(s,r-3))||d.has(id(s,r+3)));}
  function maxCopies(t,rule){if(t&&t.suit==='m'&&t.rank>1&&t.rank<9)return 0;if(t&&t.suit==='z'&&t.rank===4&&rule&&rule.northMode==='disabled')return 0;return 4;}
  function wallReduce(t,c){if(!t||!['m','p','s'].includes(t.suit))return 0;let x=0;[-2,-1,1,2].forEach(o=>{const r=t.rank+o;if(r<1||r>9)return;if((c[id(t.suit,r)]||0)>=4)x+=Math.abs(o)===1?14:7;});return clamp(x,0,24);}
  function details(state,me,t,oppIndex){const ps=players(state),opp=ps[oppIndex],th=threats(state,me).find(x=>x.playerIndex===oppIndex)||{riichi:false,dealer:false,openMeldCount:0,threatLevel:8},c=Sanma.CpuVisibleTiles?Sanma.CpuVisibleTiles.getVisibleCountsForPlayer(state,me):Object.create(null),seen=t&&t.baseId?c[t.baseId]||0:0,reasons=[];if(!t||!opp)return{danger:50,reasons:['評価対象なし'],opponentThreat:th};if(seen>=maxCopies(t,state&&state.ruleConfig))return{danger:0,reasons:['4枚見え'],opponentThreat:th};if(th.riichi&&river(opp).has(t.baseId))return{danger:2,reasons:['現物'],opponentThreat:th};let d=10+th.threatLevel*.45;if(th.riichi)reasons.push('リーチ者あり');if(th.dealer)reasons.push('親');if(th.openMeldCount)reasons.push(`副露${th.openMeldCount}`);if(t.suit==='z'){d+=seen===0?22:10;d-=seen*8;reasons.push(seen===0?'初牌字牌':'字牌見え');}else{if(t.rank>=3&&t.rank<=7){d+=t.rank===5?16:10;reasons.push('中張牌');}else if(t.rank===2||t.rank===8){d+=5;reasons.push('辺張周辺');}else{d-=5;reasons.push('端牌');}if(th.riichi&&suji(opp,t)){d-=13;reasons.push('筋');}const k=wallReduce(t,c);if(k){d-=k;reasons.push('壁');}}
    const indicators=state&&state.wall&&Array.isArray(state.wall.doraIndicators)?state.wall.doraIndicators:(state&&state.doraIndicators)||[];if(indicators.some(x=>x&&x.baseId===t.baseId)){d+=12;reasons.push('ドラ表示周辺');}return{danger:clamp(Math.round(d),0,120),reasons,opponentThreat:th};}
  function explain(state,me,t){const ts=threats(state,me);if(!ts.length)return{danger:0,reasons:['相手なし'],byOpponent:[]};const by=ts.map(x=>Object.assign({playerIndex:x.playerIndex},details(state,me,t,x.playerIndex))).sort((a,b)=>b.danger-a.danger),top=by[0];return{danger:top.danger,reasons:top.reasons||[],byOpponent:by};}
  function mode(state,me,value,shanten){const max=threats(state,me).reduce((m,t)=>Math.max(m,t.threatLevel),0),v=Number(value)||0,s=Number.isFinite(shanten)?shanten:3;if(max>=60&&s>=2&&v<55)return'fold';if(max>=75&&s>=1&&v<40)return'fold';if(max>=45&&s>=2)return'fold';if(s<=0&&v>=35)return'push';if(s<=1&&v>=55)return'push';if(max>=40)return'balanced';return s<=1?'push':'balanced';}
  Sanma.CpuRiskAnalysis={getOpponentThreats:threats,scoreTileDangerAgainstOpponent:(s,m,t,o)=>details(s,m,t,o).danger,scoreTileDanger:(s,m,t)=>explain(s,m,t).danger,explainTileDanger:explain,choosePushFoldMode:mode};
})(window);
