(function attachCpuStrategy(global){
  const Sanma=global.Sanma=global.Sanma||{};
  const seq=i=>(i>=9&&i<=17)||(i>=18&&i<=26);
  function standard(c,open){let best=8;function f(i,m,p,t){while(i<c.length&&!c[i])i+=1;if(i>=c.length){const mm=open+m,tt=Math.min(t,Math.max(0,4-mm));best=Math.min(best,8-mm*2-tt-p);return;}c[i]-=1;f(i,m,p,t);c[i]+=1;if(c[i]>=3){c[i]-=3;f(i,m+1,p,t);c[i]+=3;}if(seq(i)&&i%9<=6&&c[i+1]>0&&c[i+2]>0){c[i]-=1;c[i+1]-=1;c[i+2]-=1;f(i,m+1,p,t);c[i]+=1;c[i+1]+=1;c[i+2]+=1;}if(c[i]>=2){c[i]-=2;if(!p)f(i,m,1,t);f(i,m,p,t+1);c[i]+=2;}if(seq(i)&&i%9<=7&&c[i+1]>0){c[i]-=1;c[i+1]-=1;f(i,m,p,t+1);c[i]+=1;c[i+1]+=1;}if(seq(i)&&i%9<=6&&c[i+2]>0){c[i]-=1;c[i+2]-=1;f(i,m,p,t+1);c[i]+=1;c[i+2]+=1;}}f(0,0,0,0);return best;}
  function estimateShanten(input){const o=input||{},conv=Sanma.HandAnalysis.toCountArray(Array.isArray(o.tiles)?o.tiles:[],o.ruleConfig||{});if(!conv.isValid)return 99;const open=Math.max(0,Number(o.openMeldCount)||0),vals=[standard(conv.counts.slice(),open)];if(!open){const pairs=conv.counts.filter(x=>x>=2).length,unique=conv.counts.filter(Boolean).length;vals.push(6-pairs+Math.max(0,7-unique));if(!(o.ruleConfig&&o.ruleConfig.northMode==='disabled')){const req=[0,8,9,17,18,26,27,28,29,30,31,32,33],u=req.filter(i=>conv.counts[i]>0).length,p=req.some(i=>conv.counts[i]>=2);vals.push(13-u-(p?1:0));}}return Math.min(...vals);}
  const counts=(tiles,rule)=>Sanma.HandAnalysis.toCountArray(tiles,rule||{}).counts;
  function sequenceShape(tile,c){if(!tile||!['p','s'].includes(tile.suit))return false;const i=Sanma.HandAnalysis.getTypeIndex(tile);return[-2,-1,1,2].some(o=>{const n=i+o;return n>=0&&n<c.length&&Math.floor(n/9)===Math.floor(i/9)&&c[n]>0;});}
  function value(player,tiles,state,rule){const c=counts(tiles,rule),d=new Set(((state&&state.wall&&state.wall.doraIndicators)||(state&&state.doraIndicators)||[]).filter(Boolean).map(t=>t.baseId));let v=0;c.forEach((n,i)=>{if(n>=3)v+=24;else if(n>=2)v+=8;if(i>=27&&n>=2)v+=6;});tiles.forEach(t=>{if(!t)return;if(t.isRed)v+=8;if(d.has(t.baseId))v+=6;if(t.suit==='z'&&t.rank>=5)v+=4;});(player&&player.melds||[]).forEach(m=>{v+=m&&m.type==='kan'?24:14;});v+=(player&&player.kitaTiles||[]).length*8;return v;}
  function liveValue(tiles,rule,remaining){const c=counts(tiles,rule);let v=0;tiles.forEach(t=>{if(!t)return;const rem=Number.isInteger(remaining[t.baseId])?remaining[t.baseId]:2,i=Sanma.HandAnalysis.getTypeIndex(t);if((c[i]||0)>=2)v+=rem*3;if(['p','s'].includes(t.suit))[-2,-1,1,2].forEach(o=>{const r=t.rank+o;if(r<1||r>9)return;const id=Sanma.TileUtil.baseId(t.suit,r),n=Number.isInteger(remaining[id])?remaining[id]:2;v+=Math.abs(o)===1?n*2:n;});});return v;}
  const penalty=(mode,d)=>mode==='fold'?d*2.1:mode==='balanced'?d*.85:d*.3;
  function chooseDiscard(input){const o=input||{},p=o.player||{},hand=Array.isArray(p.hand)?p.hand:[],rule=o.ruleConfig||{},rand=typeof o.random==='function'?o.random:Math.random;if(!hand.length)return{tileInstanceId:null,reason:'手牌がありません。',candidates:[],score:0};const c=counts(hand,rule),open=(p.melds||[]).length,current=estimateShanten({tiles:hand,ruleConfig:rule,openMeldCount:open}),hv=value(p,hand,o.state,rule),mode=Sanma.CpuRiskAnalysis&&o.state?Sanma.CpuRiskAnalysis.choosePushFoldMode(o.state,p.id,hv,current):'balanced',seen=Sanma.CpuVisibleTiles&&o.state?Sanma.CpuVisibleTiles.getVisibleCountsForPlayer(o.state,p.id):Object.create(null),remaining=Sanma.CpuVisibleTiles&&o.state?Sanma.CpuVisibleTiles.getRemainingByBaseId(o.state,p.id):Object.create(null),win=Boolean(o.analysis&&o.analysis.scoreResult&&o.analysis.scoreResult.isValidWin);const cand=hand.map((t,i)=>{const left=hand.slice();left.splice(i,1);const sh=estimateShanten({tiles:left,ruleConfig:rule,openMeldCount:open}),tenpai=sh<=0,type=Sanma.HandAnalysis.getTypeIndex(t),n=c[type]||0,reasons=[];let score=-sh*35;if(t.suit==='z'&&n===1){score+=30;reasons.push('孤立字牌');}if((t.suit==='m'||t.rank===1||t.rank===9)&&n===1){score+=16;reasons.push('孤立端牌');}if(n>=2){score-=15;reasons.push('対子を崩す');}if(sequenceShape(t,c)){score-=20;reasons.push('筋牌形を崩す');}if(tenpai){score+=60;reasons.push('聴牌維持');}if(win){score+=1000;reasons.push('和了可能');}if(t.isRed&&n>=2){score-=8;reasons.push('赤牌を温存');}if(!reasons.length)reasons.push('シャンテン優先');const handValue=value(p,left,o.state,rule),lv=liveValue(left,rule,remaining),risk=Sanma.CpuRiskAnalysis&&o.state?Sanma.CpuRiskAnalysis.explainTileDanger(o.state,p.id,t):{danger:0,reasons:[]};score+=handValue*.12+lv*.25-penalty(mode,risk.danger);const rem=Number.isInteger(remaining[t.baseId])?remaining[t.baseId]:null;if(rem===0){score+=mode==='fold'?26:14;reasons.push('可視残り0枚');}else if(rem!==null)reasons.push(`可視残り${rem}枚`);if(mode==='fold'&&risk.danger<=12){score+=18;reasons.push('安全寄せ');}if(risk.danger>=70)reasons.push('危険度高');const tie=rand();return{tileInstanceId:t.instanceId,tileLabel:Sanma.TileUtil.getTileAriaLabel(t),tileType:t.baseId,visibleCount:seen[t.baseId]||0,remainingVisibleEstimate:rem,danger:risk.danger,dangerReasons:risk.reasons,pushFoldMode:mode,handValue,liveShapeValue:lv,safetyReason:risk.danger<=12?(risk.reasons[0]||'低危険度'):null,score:score+tie/1000,baseScore:score,shanten:sh,tenpai,reasons,tieBreaker:tie};}).sort((a,b)=>b.score-a.score||String(a.tileInstanceId).localeCompare(String(b.tileInstanceId)));const s=cand[0];return{tileInstanceId:s.tileInstanceId,reason:`${s.reasons.join('、')}。シャンテン推定 ${s.shanten}。`,candidates:cand,score:s.baseScore,pushFoldMode:s.pushFoldMode,danger:s.danger,handValue:s.handValue};}
  const locked=p=>Boolean(p&&(p.hasRiichi||(p.riichi&&(p.riichi.pending||p.riichi.declared))));
  const callId=c=>String((c&&(c.actionId||c.action||c.id))||(c&&c.option&&c.option.type)||'').toLowerCase();
  const callOpt=c=>c&&c.option?c.option:c||{};
  function yakuhai(c,p,state){const t=callOpt(c).tile||(state&&state.lastDiscard&&state.lastDiscard.tile);if(!t||t.suit!=='z')return false;if(t.rank>=5)return true;const wr=w=>({east:1,south:2,west:3,north:4}[w]||0),round=state&&state.round||{};return t.rank===wr(p&&p.seatWind)||t.rank===wr(round.roundWind||'east');}
  function afterCall(c,p,state){const ids=new Set(callOpt(c).consumeInstanceIds||[]),hand=Array.isArray(p&&p.hand)?p.hand:[];if(!ids.size)return 99;const left=hand.filter(t=>!ids.has(t.instanceId));if(left.length!==hand.length-ids.size)return 99;return estimateShanten({tiles:left,ruleConfig:state&&state.ruleConfig||{},openMeldCount:(p.melds||[]).length+1});}
  function chooseCall(input){const o=input||{},state=o.state||{},fallback=o.player||{},calls=Array.isArray(o.legalCalls)?o.legalCalls.filter(Boolean):[],rand=typeof o.random==='function'?o.random:()=>0;if(!calls.length)return null;const ranked=[];calls.forEach((c,index)=>{const p=Array.isArray(state.players)&&Number.isInteger(c.playerIndex)&&state.players[c.playerIndex]||fallback;if(locked(p))return;const action=callId(c),opt=callOpt(c),type=opt.type||c.type;if(!['pon','chi','kan'].includes(action)&&type!=='minkan')return;const before=estimateShanten({tiles:Array.isArray(p.hand)?p.hand:[],ruleConfig:state.ruleConfig||{},openMeldCount:(p.melds||[]).length}),after=afterCall(c,p,state);if(action==='kan'||type==='minkan'){if(type!=='minkan'||after>before)return;const live=state.wall&&typeof state.wall.remainingCount==='function'?state.wall.remainingCount():70,hv=value(p,(p.hand||[]).filter(t=>!(new Set(opt.consumeInstanceIds||[])).has(t.instanceId)),state,state.ruleConfig||{})+28,mode=Sanma.CpuRiskAnalysis?Sanma.CpuRiskAnalysis.choosePushFoldMode(state,p.id,hv,after):'balanced';let score=(before-after)*38+hv+rand();if(after<=0)score+=64;else if(after===1)score+=28;if(yakuhai(c,p,state))score+=18;if(live<=8)score-=36;if(mode==='fold')score-=after<=0&&hv>=70?12:58;if(after<=before&&score>=58&&!(mode==='fold'&&after>0)&&live>0)ranked.push({c,index,score});return;}if(!['pon','chi'].includes(action)||after>before)return;let score=(before-after)*30+rand();if(action==='pon'&&yakuhai(c,p,state))score+=60;score+=action==='pon'?8:4;ranked.push({c,index,score});});ranked.sort((a,b)=>b.score-a.score||Number(a.c.priority||0)-Number(b.c.priority||0)||a.index-b.index);return ranked.length?ranked[0].c:null;}
  Sanma.CpuStrategy={chooseDiscard,estimateShanten,chooseCall};
})(window);
