(function attachGameEnginePart3(global){
const Sanma=global.Sanma=global.Sanma||{};
Object.assign(Sanma.GameEngine.prototype,{
requestHumanKan(optionIndex=0){if(this.phase!=='human-discard'&&this.phase!=='human-call')return false;const action=Sanma.ActionResolver.findAction(this,this.humanPlayer.id,'kan');const option=action&&action.options&&action.options[optionIndex];if(!option){this.addLog('現在カンできません。');return false;}return this.applyKan(this.humanPlayer.id,option);},
selectHumanKan(optionIndex){return this.requestHumanKan(optionIndex);},
discardHumanTile(instanceId){if(!this.humanPlayer||this.turnIndex!==this.humanPlayer.id||!['human-discard','caller-discard'].includes(this.phase))return false;if(this.humanPlayer.riichi&&this.humanPlayer.riichi.pending&&!Sanma.RiichiRules.canDeclareDiscard(this,this.humanPlayer.id,this.humanPlayer.hand.find(t=>t.instanceId===instanceId))){this.addLog('聴牌を維持するリーチ宣言牌を選んでください。');return false;}if(this.humanPlayer.hasRiichi&&this.humanPlayer.lastDraw&&instanceId!==this.humanPlayer.lastDraw.instanceId){this.addLog('リーチ後はツモ切りのみです。');return false;}const tile=this.humanPlayer.discardTileByInstanceId(instanceId);if(!tile)return false;return this.afterDiscard(this.humanPlayer,tile);},
skipHumanCall(){if(this.phase!=='human-call'||!this.callWindow)return false;const w=this.callWindow;this.callWindow=null;if(w.pendingCpuRonCandidates&&w.pendingCpuRonCandidates.length)return this.resolveRonCandidates(w.pendingCpuRonCandidates,w.fromPlayerIndex);if(w.pendingCpuCallCandidates&&w.pendingCpuCallCandidates.length){const choice=Sanma.CpuStrategy.chooseCall({state:this,player:this.players[w.pendingCpuCallCandidates[0].playerIndex],legalCalls:w.pendingCpuCallCandidates,random:this.cpuRandom});if(choice)return this.applyCpuCall(choice);}return this.advanceAfterDiscard(w.fromPlayerIndex);},
applyOpenCall(playerIndex,actionId,option){const caller=this.players[playerIndex],discarder=this.players[option.fromPlayerIndex];if(!caller||!discarder)return false;const consumed=[];for(const id of option.consumeInstanceIds||[]){const i=caller.hand.findIndex(t=>t.instanceId===id);if(i<0)return false;consumed.push(caller.hand.splice(i,1)[0]);}const di=discarder.discards.findIndex(t=>t.instanceId===option.tile.instanceId);if(di<0)return false;const called=discarder.discards.splice(di,1)[0];caller.melds.push({type:actionId,tiles:consumed.concat(called).sort(Sanma.TileUtil.compareTiles),fromPlayerIndex:option.fromPlayerIndex,open:true});caller.lastDraw=null;Sanma.RiichiRules&&Sanma.RiichiRules.clearIppatsu(this);this.turnIndex=playerIndex;this.lastDiscard=null;this.callWindow=null;this.phase=caller.isHuman?'caller-discard':'cpu-running';this.recordGameEvent('call',{playerIndex,action:actionId,fromPlayerIndex:option.fromPlayerIndex});this.addLog(`${caller.name}が${actionId==='pon'?'ポン':'チー'}しました。`);this.emitChange();if(!caller.isHuman)this.runCpuUntilHumanTurn();return true;},
resolveExhaustiveDraw(){const status=this.players.map(p=>{const a=Sanma.HandAnalysis.analyzeTenpaiWithMelds?Sanma.HandAnalysis.analyzeTenpaiWithMelds(p.hand,p.melds,this.ruleConfig):Sanma.HandAnalysis.analyzeTenpai(p.hand,this.ruleConfig);return{playerIndex:p.id,isTenpai:Boolean(a.isTenpai),waits:a.waits||[]};}),tenpai=status.filter(s=>s.isTenpai).map(s=>s.playerIndex),settlement=Sanma.Settlement.applyExhaustiveDrawSettlement({players:this.players,tenpaiPlayers:tenpai,ruleConfig:this.ruleConfig});return this.endRound({type:'exhaustive_draw',dealerTenpai:tenpai.includes(this.round.dealerIndex),tenpaiPlayers:tenpai,notenPlayers:status.filter(s=>!s.isTenpai).map(s=>s.playerIndex),tenpaiStatus:status,settlement,drawSettlement:settlement});},
drawForHumanManually(){if(this.turnIndex!==this.humanPlayer.id)return false;this.drawFor(this.humanPlayer);if(this.phase!=='round-ended'){if(!this.tryTsumo(this.humanPlayer.id))this.phase='human-discard';}this.emitChange();return true;},
finalizePendingKan(){return false;},
resolvePendingCpuRon(discarderIndex){if(this.callWindow&&this.callWindow.pendingCpuRonCandidates)return this.resolveRonCandidates(this.callWindow.pendingCpuRonCandidates,discarderIndex);return false;}
});
})(window);
