(function attachGameEnginePart1(global){
const Sanma=global.Sanma=global.Sanma||{};
Object.assign(Sanma.GameEngine.prototype,{
declareHumanRiichi(){if(this.phase!=='human-discard')return false;const r=Sanma.RiichiManager.declare(this,this.humanPlayer.id);if(r.applied){this.matchManager.syncRound(this.round);this.recordGameEvent('riichi',{playerIndex:this.humanPlayer.id});this.addLog(r.reason);this.emitChange();return true;}this.addLog(r.reason);this.emitChange();return false;},
applyKan(playerIndex,option){const r=Sanma.KanRules.applyKan({state:this,playerIndex,kanAction:option,ruleConfig:this.ruleConfig});if(!r.applied){this.addLog(r.reason);return false;}this.turnIndex=playerIndex;this.phase=this.players[playerIndex].isHuman?'human-discard':'cpu-running';this.recordGameEvent('kan',{playerIndex,type:r.kanType,replacement:this.tileSnapshot(r.replacement),doraIndicator:this.tileSnapshot(r.doraIndicator)});this.addLog(r.reason);if(r.replacement&&this.tryTsumo(playerIndex))return true;this.emitChange();if(!this.players[playerIndex].isHuman)this.runCpuUntilHumanTurn();return true;},
collectReactions(discarderIndex){const out=[];for(const p of this.players){if(p.id===discarderIndex)continue;const actions=this.getAvailableActions(p.id),ron=actions.find(a=>a.id==='ron'&&a.enabled),calls=[];for(const id of ['kan','pon','chi']){const a=actions.find(x=>x.id===id&&x.enabled);for(const option of a&&a.options||[])calls.push({playerIndex:p.id,actionId:id,option,priority:id==='kan'?2:id==='pon'?3:4});}out.push({playerIndex:p.id,ron:ron&&ron.analysis||null,calls});}return out;},
claimHumanCall(actionId,optionIndex=0){if(actionId==='ron')return this.claimHumanRon();if(this.phase!=='human-call'||!this.callWindow)return false;const action=this.callWindow.actions.find(a=>a.id===actionId),option=action&&action.options&&action.options[optionIndex];if(!option)return false;if(actionId==='kan'){this.callWindow=null;return this.applyKan(this.humanPlayer.id,option);}return this.applyOpenCall(this.humanPlayer.id,actionId,option);},
applyCpuCall(c){return c.actionId==='kan'?this.applyKan(c.playerIndex,c.option):this.applyOpenCall(c.playerIndex,c.actionId,c.option);},
tryTsumo(playerIndex){const a=Sanma.ActionResolver.findAction(this,playerIndex,'tsumo');if(a&&a.enabled){if(this.players[playerIndex].isHuman)return false;return this.resolveWin(playerIndex,a.analysis,'tsumo',null);}return false;},
claimHumanTsumo(){if(this.phase!=='human-discard')return false;const a=Sanma.ActionResolver.findAction(this,this.humanPlayer.id,'tsumo');return a&&a.enabled?this.resolveWin(this.humanPlayer.id,a.analysis,'tsumo',null):false;},
claimHumanRon(){if(this.phase!=='human-call'||!this.callWindow)return false;const a=this.callWindow.actions.find(x=>x.id==='ron'&&x.enabled);return a?this.resolveWin(this.humanPlayer.id,a.analysis,'ron',this.callWindow.fromPlayerIndex):false;},
resolveWin(playerIndex,analysis,winType,loserIndex){if(!analysis||!analysis.scoreResult||!analysis.scoreResult.isValidWin)return false;const context=Object.assign({},analysis.context,{winnerIndex:playerIndex,loserIndex,winType});const settlement=Sanma.Settlement.applySettlement({players:this.players,scoreResult:analysis.scoreResult,context});if(!settlement.applied)return false;return this.endRound({type:'win',winnerIndex:playerIndex,winnerIndexes:[playerIndex],winType,fromPlayerIndex:loserIndex,yaku:analysis.yakuResult,score:analysis.scoreResult,settlement});},
endRound(result){this.winResult=result;this.phase=result.type==='win'||result.type==='double_ron'?'win-ended':'round-ended';this.callWindow=null;this.matchManager.syncRound(this.round);this.matchManager.completeRound(result,this.players);this.round.riichiSticks=this.matchManager.state.riichiSticks;Sanma.GameRecord.completeRound(this.gameRecord,result,this.players.map(p=>p.points),{dealerIndex:this.round.dealerIndex,honba:this.round.honba,riichiSticks:this.round.riichiSticks,pointMovement:result.settlement&&result.settlement.changes||[]});if(this.matchManager.state.matchEnded)Sanma.GameRecord.finishMatch(this.gameRecord,this.players.map(p=>p.points),this.matchManager.state.rankings,this.matchManager.state.endReason);this.recordGameEvent(result.type==='exhaustive_draw'?'draw_end':'win',{result:Sanma.GameRecord.compactResult(result)});this.addLog(result.type==='exhaustive_draw'?'流局しました。':`${this.players[result.winnerIndex].name}が和了しました。`);this.syncStateMachine('round-end');this.emitChange();return true;}
});
})(window);
