(function attachGameRecord(global) {
  const Sanma = global.Sanma = global.Sanma || {};
  const MAX_EVENTS_PER_ROUND = 300, MAX_IMPORT_CHARS = 1024*1024, MAX_ROUNDS = 64, MAX_STRING_LENGTH = 2048, REQUIRED_PLAYER_COUNT = 3, MAX_REASONABLE_POINTS = 300000;
  let seq = 0;
  const YAKU_DISPLAY_NAMES = Object.freeze({ honitsu:'混一色',chinitsu:'清一色',ikkitsuukan:'一気通貫',ittsu:'一気通貫',chanta:'混全帯么九',junchan:'純全帯么九',sanankou:'三暗刻',sankantsu:'三槓子',shousangen:'小三元',sanshokuDoukou:'三色同刻',sanshoku_doukou:'三色同刻',ryanpeikou:'二盃口',suuankou:'四暗刻',suuankouTanki:'四暗刻単騎',daisangen:'大三元',tsuuiisou:'字一色',shousuushii:'小四喜',daisuushii:'大四喜',chinroutou:'清老頭',ryuuiisou:'緑一色',chuurenPoutou:'九蓮宝燈',chuuren_poutou:'九蓮宝燈',junseiChuurenPoutou:'純正九蓮宝燈',suukantsu:'四槓子','suuankou-tanki':'四暗刻単騎','kokushi-musou':'国士無双','kokushi-musou-13-wait':'国士無双十三面待ち','sanshoku-doukou':'三色同刻','chuuren-poutou':'九蓮宝燈','chuuren-9-wait':'純正九蓮宝燈' });
  const clone = v => v === undefined ? null : JSON.parse(JSON.stringify(v));
  const obj = v => !!(v && typeof v === 'object' && !Array.isArray(v));
  function yakuDisplayName(v){ if(v==null)return ''; if(typeof v==='string')return YAKU_DISPLAY_NAMES[v]||v; if(!obj(v))return String(v||''); const k=v.displayName||v.label||v.name||v.id||v.key||''; return YAKU_DISPLAY_NAMES[k]||k; }
  function normalizeYakuArray(a){ return (Array.isArray(a)?a:[]).map(yakuDisplayName).filter(Boolean); }
  function validateStringLengths(root){ const q=[root]; while(q.length){ const v=q.pop(); if(typeof v==='string'&&v.length>MAX_STRING_LENGTH)throw new Error(`牌譜内の文字列は${MAX_STRING_LENGTH}文字以内で指定してください。`); if(Array.isArray(v))q.push(...v); else if(obj(v))q.push(...Object.keys(v),...Object.values(v)); } }
  function playerIndex(v,label,allowNull=true){ if(v===undefined||(v===null&&allowNull))return; if(!Number.isInteger(v)||v<0||v>=REQUIRED_PLAYER_COUNT)throw new Error(`${label} is out of range.`); }
  function validateScore(s,label='局結果'){ if(s==null)return; if(!obj(s))throw new Error(`${label}のscore形式が不正です。`); for(const k of ['isValidWin','isYakuman'])if(s[k]!==undefined&&typeof s[k]!=='boolean')throw new Error(`${label}のscore.${k}は真偽値で指定してください。`); for(const k of ['han','fu','yakumanCount','basePoints'])if(s[k]!==undefined&&s[k]!==null&&!Number.isFinite(s[k]))throw new Error(`${label}のscore.${k}は数値で指定してください。`); }
  function validateResult(r){ if(r==null)return; if(!obj(r))throw new Error('局結果の形式が不正です。'); for(const k of ['yaku','yakuman','winners','tenpaiPlayers','notenPlayers','tenpaiStatus'])if(r[k]!==undefined&&!Array.isArray(r[k]))throw new Error(`局結果の${k}は配列で指定してください。`); playerIndex(r.winnerIndex,'result.winnerIndex'); playerIndex(r.fromPlayerIndex,'result.fromPlayerIndex'); for(const k of ['tenpaiPlayers','notenPlayers']) if(Array.isArray(r[k])) r[k].forEach(v=>playerIndex(v,`result.${k}`,false)); if(Array.isArray(r.pointTransfers)) r.pointTransfers.forEach((t,i)=>{ if(!obj(t))throw new Error(`pointTransfers[${i}] is invalid.`); playerIndex(t.fromPlayerIndex,`pointTransfers[${i}].fromPlayerIndex`,false); playerIndex(t.toPlayerIndex,`pointTransfers[${i}].toPlayerIndex`,false); if(!Number.isFinite(Number(t.points))||Number(t.points)<0||Number(t.points)>MAX_REASONABLE_POINTS)throw new Error(`pointTransfers[${i}].points is invalid.`); }); if(Array.isArray(r.winners))r.winners.forEach(w=>{ if(!obj(w)||!Number.isInteger(w.winnerIndex)||w.winnerIndex<0||w.winnerIndex>=3)throw new Error('局結果のwinners.winnerIndexが不正です。'); if(w.yaku!==undefined&&!Array.isArray(w.yaku))throw new Error('局結果のwinners.yakuは配列で指定してください。'); if(w.yakuman!==undefined&&!Array.isArray(w.yakuman))throw new Error('局結果のwinners.yakumanは配列で指定してください。'); validateScore(w.score,'局結果のwinners'); }); validateScore(r.score); if(r.changes!==undefined&&!Array.isArray(r.changes))throw new Error('局結果のchangesは配列で指定してください。'); if(r.pointTransfers!==undefined&&!Array.isArray(r.pointTransfers))throw new Error('局結果のpointTransfersは配列で指定してください。'); }
  function validateImportedRecord(r){
    if(!obj(r)||typeof r.id!=='string'||!r.id.trim()||!Array.isArray(r.rounds)||!r.rounds.length)throw new Error('牌譜データの形式が不正です。');
    if(!Array.isArray(r.players)||r.players.length!==3)throw new Error('牌譜のプレイヤー数は3人である必要があります。');
    const ids=r.players.map(p=>p&&p.id).slice().sort((a,b)=>a-b); if(!ids.every(Number.isInteger)||ids.some((id,i)=>id!==i))throw new Error('牌譜のプレイヤーIDは0、1、2を重複なく指定してください。');
    if(r.rounds.length>MAX_ROUNDS)throw new Error(`牌譜の局数は${MAX_ROUNDS}局以内で指定してください。`); if(typeof r.seed==='string'&&r.seed.length>128)throw new Error('牌譜のseedは128文字以内で指定してください。');
    if(r.finalPoints!==undefined){ if(!Array.isArray(r.finalPoints))throw new Error('finalPointsは配列で指定してください。'); if(r.finalPoints.length&&r.finalPoints.length!==3)throw new Error('finalPointsは3人分指定してください。'); r.finalPoints.forEach(p=>{if(!Number.isFinite(Number(p))||Number(p)<0||Number(p)>MAX_REASONABLE_POINTS)throw new Error('finalPointsが妥当な点数範囲を超えています。');}); }
    validateStringLengths(r); r.rounds.forEach(round=>{ if(!obj(round)||!Array.isArray(round.events))throw new Error('局データの形式が不正です。'); if(round.events.length>MAX_EVENTS_PER_ROUND)throw new Error(`1局のイベント数は${MAX_EVENTS_PER_ROUND}件以内で指定してください。`); validateResult(round.result); }); return true;
  }
  function deserializeImported(text){ const s=String(text||''); if(s.length>MAX_IMPORT_CHARS)throw new Error(`牌譜JSONは${MAX_IMPORT_CHARS}文字以内で指定してください。`); const r=JSON.parse(s); validateImportedRecord(r); return normalize(r); }
  const playerSnapshot=p=>({id:p.id,name:p.name,seatWind:p.seatWind,isHuman:Boolean(p.isHuman),initialPoints:Number(p.points)||0});
  function createRound(o={}){ return {roundLabel:o.roundLabel||'東1局',honba:Number(o.honba)||0,dealerIndex:Number.isInteger(o.dealerIndex)?o.dealerIndex:0,riichiSticks:Number(o.riichiSticks)||0,startingPoints:(o.startingPoints||[]).map(p=>Number(p)||0),events:[],result:null,pointMovement:[]}; }
  const currentRound=r=>r&&Array.isArray(r.rounds)?r.rounds[r.rounds.length-1]:null;
  const protectedEvent=e=>!!(e&&['deal','round_start','win','score_settlement','double_ron'].includes(e.type));
  function pruneEvents(events){ if(!Array.isArray(events)||events.length<=MAX_EVENTS_PER_ROUND)return Array.isArray(events)?events:[]; const out=events.slice(); let removed=false; while(out.length>MAX_EVENTS_PER_ROUND){ const i=out.findIndex((e,n)=>n>0&&!protectedEvent(e)); if(i>=0)out.splice(i,1); else out.splice(0,out.length-MAX_EVENTS_PER_ROUND); removed=true; } if(removed&&obj(out[0]))out[0].pruned=true; return out; }
  function closeOpenRound(record,reason){ const round=currentRound(record); if(!round||round.result)return round; round.result={type:'recovered_reset',winnerIndex:null,winners:[],winType:null,dealerTenpai:false,yaku:[],yakuman:[],score:{isValidWin:false,isYakuman:false,han:0,fu:null,yakumanCount:0,basePoints:0,limitName:''},changes:[],reason:reason||'Recovery reset closed this unfinished round.',recovery:true,aborted:true}; round.recovery={type:'reset_current_round',reason:round.result.reason,at:new Date().toISOString()}; return round; }
  function create(o={}){ seq++; return {version:2,eventSchemaVersion:2,id:`record-${Date.now().toString(36)}-${seq.toString(36)}`,matchId:String(o.matchId||''),phase:16,phaseLabel:'16',createdAt:new Date().toISOString(),seed:Sanma.SeedPolicy?Sanma.SeedPolicy.requireValidSeed(o.seed):String(o.seed||''),ruleConfig:clone(o.ruleConfig||{}),players:(o.players||[]).map(playerSnapshot),rounds:[createRound(o)],finalPoints:[],finalRankings:[],matchEndReason:'',completedAt:null}; }
  function addRound(record,o={}){ if(!record||!Array.isArray(record.rounds)||record.completedAt)return null; closeOpenRound(record,'A new round was started after recovery before the previous round completed.'); const r=createRound(o); record.rounds.push(r); return r; }
  function addEvent(record,type,data){ const round=currentRound(record); if(!round||!type||record.completedAt)return null; const event={index:round.events.length?round.events[round.events.length-1].index+1:1,type,at:new Date().toISOString(),data:clone(data||{})}; round.events.push(event); if(round.events.length>MAX_EVENTS_PER_ROUND)round.events=pruneEvents(round.events); return event; }
  function compactScore(s={}){ return {isValidWin:Boolean(s.isValidWin),isYakuman:Boolean(s.isYakuman),han:Number(s.han)||0,fu:s.fu==null?null:Number(s.fu),yakumanCount:Number(s.yakumanCount)||0,basePoints:Number(s.basePoints)||0,limitName:s.limitName||''}; }
  function groups(input){ const y=input&&input.yaku?input.yaku:{}; if(Array.isArray(y))return {yaku:normalizeYakuArray(y),yakuman:[]}; return {yaku:normalizeYakuArray((y.yaku||[]).concat(y.dora||[])),yakuman:normalizeYakuArray(y.yakuman||[])}; }
  function compactWinner(w,f={}){ const s=Object.assign({},f,w||{}),g=groups(s); return {winnerIndex:Number.isInteger(s.winnerIndex)?s.winnerIndex:null,winType:s.winType||null,fromPlayerIndex:Number.isInteger(s.fromPlayerIndex)?s.fromPlayerIndex:null,yaku:g.yaku,yakuman:normalizeYakuArray(s.yakuman).concat(g.yakuman).filter((x,i,a)=>a.indexOf(x)===i),score:compactScore(s.score||{}),pointTransfers:Array.isArray(s.pointTransfers)?clone(s.pointTransfers):[]}; }
  function compactResult(input={}){ const settlement=input.settlement||{}, changes=Array.isArray(settlement.changes)?settlement.changes:(input.changes||[]), winners=Array.isArray(input.winners)&&input.winners.length?input.winners.map(w=>compactWinner(w,input)):(Number.isInteger(input.winnerIndex)?[compactWinner(input,{})]:[]), first=winners[0]||null,g=groups(input), type=winners.length>1||input.isMultiRon?'double_ron':(input.type||(winners.length?'win':'exhaustive_draw')); const ds=input.drawSettlement||(type==='exhaustive_draw'?input.settlement:null); return {type,winnerIndex:first?first.winnerIndex:null,winners,winType:first?first.winType:(input.winType||null),fromPlayerIndex:Number.isInteger(input.fromPlayerIndex)?input.fromPlayerIndex:null,dealerTenpai:Boolean(input.dealerTenpai),tenpaiPlayers:Array.isArray(input.tenpaiPlayers)?input.tenpaiPlayers.slice():[],notenPlayers:Array.isArray(input.notenPlayers)?input.notenPlayers.slice():[],tenpaiStatus:Array.isArray(input.tenpaiStatus)?clone(input.tenpaiStatus):[],drawSettlement:ds&&obj(ds)?{applied:Boolean(ds.applied),type:ds.type||'exhaustive_draw',mode:ds.mode||'noten-bappu-3000',tenpaiPlayers:Array.isArray(ds.tenpaiPlayers)?ds.tenpaiPlayers.slice():[],notenPlayers:Array.isArray(ds.notenPlayers)?ds.notenPlayers.slice():[],changes:(ds.changes||[]).map(c=>({playerIndex:c.playerIndex,delta:c.delta,after:c.after})),reason:ds.reason||''}:null,yaku:normalizeYakuArray(input.yaku).concat(g.yaku).filter((x,i,a)=>a.indexOf(x)===i),yakuman:normalizeYakuArray(input.yakuman).concat(g.yakuman).filter((x,i,a)=>a.indexOf(x)===i),score:compactScore(input.score||(first&&first.score)||{}),changes:(changes||[]).map(c=>({playerIndex:c.playerIndex,delta:c.delta,after:c.after})),pointTransfers:Array.isArray(input.pointTransfers)?clone(input.pointTransfers):[],reason:input.reason||''}; }
  function completeRound(record,result,finalPoints,meta={}){ const round=currentRound(record); if(!round||record.completedAt)return record; round.result=compactResult(result); if(Number.isInteger(meta.dealerIndex))round.dealerIndex=meta.dealerIndex; if(Number.isFinite(meta.honba))round.honba=meta.honba; if(Number.isFinite(meta.riichiSticks))round.riichiSticks=meta.riichiSticks; round.pointMovement=Array.isArray(meta.pointMovement)?clone(meta.pointMovement):(round.result.changes||[]).map(c=>({playerIndex:c.playerIndex,delta:c.delta,after:c.after})); record.finalPoints=(finalPoints||[]).map(p=>Number(p)||0); return record; }
  function finishMatch(record,points,rankings,reason){ if(!record||record.completedAt)return record; record.finalPoints=(points||[]).map(p=>Number(p)||0); record.finalRankings=clone(rankings||[]); record.matchEndReason=reason||''; record.completedAt=new Date().toISOString(); return record; }
  function finishRound(record,result,points){ completeRound(record,result,points); return finishMatch(record,points,[],''); }
  function normalizeWinner(w){ return obj(w)?compactWinner(w,{}):null; }
  function normalizeResult(r){ if(!obj(r))return r||null; const n=clone(r); n.winners=(Array.isArray(n.winners)?n.winners:(Number.isInteger(n.winnerIndex)?[n]:[])).map(normalizeWinner).filter(Boolean); n.winnerIndex=n.winners.length?n.winners[0].winnerIndex:null; n.yaku=normalizeYakuArray(n.yaku); n.yakuman=normalizeYakuArray(n.yakuman); n.score=compactScore(n.score||(n.winners[0]&&n.winners[0].score)||{}); n.changes=Array.isArray(n.changes)?n.changes:[]; n.pointTransfers=Array.isArray(n.pointTransfers)?n.pointTransfers:[]; n.tenpaiPlayers=Array.isArray(n.tenpaiPlayers)?n.tenpaiPlayers:[]; n.notenPlayers=Array.isArray(n.notenPlayers)?n.notenPlayers:[]; n.tenpaiStatus=Array.isArray(n.tenpaiStatus)?n.tenpaiStatus:[]; if(n.drawSettlement===undefined)n.drawSettlement=null; return n; }
  function normalize(record){ if(!record||typeof record!=='object'||!record.id||!Array.isArray(record.rounds)||!record.rounds.length)throw new Error('牌譜データの形式が不正です。'); const n=clone(record); n.version=Math.max(Number(n.version)||1,2); n.eventSchemaVersion=Math.max(Number(n.eventSchemaVersion)||1,2); n.matchId=typeof n.matchId==='string'?n.matchId:''; n.phase=Number(n.phase)||8; n.phaseLabel=typeof n.phaseLabel==='string'?n.phaseLabel:String(n.phase||''); n.rounds.forEach(r=>{ if(!obj(r))throw new Error('局データの形式が不正です。'); r.roundLabel=r.roundLabel||'東1局'; r.honba=Number(r.honba)||0; r.dealerIndex=Number.isInteger(r.dealerIndex)?r.dealerIndex:0; r.riichiSticks=Number(r.riichiSticks)||0; r.startingPoints=Array.isArray(r.startingPoints)?r.startingPoints:[]; r.pointMovement=Array.isArray(r.pointMovement)?r.pointMovement:[]; r.result=normalizeResult(r.result); r.events=Array.isArray(r.events)?pruneEvents(r.events):[]; }); n.players=Array.isArray(n.players)?n.players:[]; n.finalPoints=Array.isArray(n.finalPoints)?n.finalPoints:[]; n.finalRankings=Array.isArray(n.finalRankings)?n.finalRankings:[]; n.matchEndReason=typeof n.matchEndReason==='string'?n.matchEndReason:''; return n; }
  const serialize=r=>JSON.stringify(normalize(r)); const deserialize=s=>normalize(JSON.parse(s));
  Sanma.GameRecord={MAX_EVENTS_PER_ROUND,MAX_IMPORT_CHARS,MAX_ROUNDS,MAX_STRING_LENGTH,REQUIRED_PLAYER_COUNT,YAKU_DISPLAY_NAMES,yakuDisplayName,normalizeYakuArray,create,addRound,addEvent,pruneEvents,closeOpenRound,compactResult,completeRound,finishMatch,finishRound,normalize,serialize,deserialize,deserializeImported,validateImportedRecord};
})(window);
