(function attachGameEnginePart2(global){
const Sanma=global.Sanma=global.Sanma||{};
Object.assign(Sanma.GameEngine.prototype,{
requestHumanKita(instanceId){if(this.phase!=='human-discard')return false;const r=Sanma.KitaManager.extract(this,this.humanPlayer.id,instanceId);if(!r.applied){this.addLog(r.reason);return false;}Sanma.RiichiRules&&Sanma.RiichiRules.clearIppatsu(this);this.recordGameEvent('kita',{playerIndex:this.humanPlayer.id,tile:this.tileSnapshot(r.extracted)});this.addLog(r.reason);if(r.replacement&&this.tryTsumo(this.humanPlayer.id))return true;this.emitChange();return true;},
afterDiscard(player,tile){this.lastDiscard={playerIndex:player.id,tile,isFinalDrawDiscard:this.wall.remainingCount()<=0&&!this.lastDrawContext?.isRinshan};this.lastDrawContext=null;this.recordGameEvent('discard',{playerIndex:player.id,tile:this.tileSnapshot(tile)});if(Sanma.RiichiRules&&Sanma.RiichiRules.handleDiscard)Sanma.RiichiRules.handleDiscard(this,player.id,tile);const reactions=this.collectReactions(player.id);const human=reactions.find(r=>r.playerIndex===this.humanPlayer.id);const cpuRon=reactions.filter(r=>!this.players[r.playerIndex].isHuman&&r.ron);const cpuCalls=reactions.flatMap(r=>r.calls||[]).filter(c=>!this.players[c.playerIndex].isHuman);
      if(human&&(human.ron||human.calls.length)){this.callWindow={isOpen:true,playerIndex:human.playerIndex,fromPlayerIndex:player.id,tile,actions:[...(human.ron?[{id:'ron',label:'ロン',enabled:true,analysis:human.ron}]:[]),...human.calls.map(c=>({id:c.actionId,label:c.actionId==='pon'?'ポン':c.actionId==='chi'?'チー':'カン',enabled:true,options:[c.option]}))],pendingCpuRonCandidates:cpuRon,pendingCpuCallCandidates:cpuCalls};this.phase='human-call';this.syncStateMachine('reaction');this.emitChange();return true;}
      if(cpuRon.length)return this.resolveRonCandidates(cpuRon,player.id);
      if(cpuCalls.length){const choice=Sanma.CpuStrategy.chooseCall({state:this,player:this.players[cpuCalls[0].playerIndex],legalCalls:cpuCalls,random:this.cpuRandom});if(choice)return this.applyCpuCall(choice);}
      return this.advanceAfterDiscard(player.id);
    },
advanceAfterDiscard(discarderIndex){if(this.wall.remainingCount()<=0)return this.resolveExhaustiveDraw();this.turnIndex=(discarderIndex+1)%this.players.length;const p=this.players[this.turnIndex];if(p.isHuman){this.phase='human-draw';this.drawFor(p);if(this.phase==='round-ended')return true;if(this.tryTsumo(p.id))return true;this.phase='human-discard';this.syncStateMachine('human-turn');this.emitChange();return true;}this.phase='cpu-running';this.syncStateMachine('cpu-turn');this.runCpuUntilHumanTurn();return true;},
resolveRonCandidates(candidates,loserIndex){const valid=candidates.filter(c=>c.ron||c.analysis).map(c=>({playerIndex:c.playerIndex,analysis:c.ron||c.analysis}));if(!valid.length)return this.advanceAfterDiscard(loserIndex);if(!this.ruleConfig.doubleRonPolicy.allowed||valid.length===1)return this.resolveWin(valid[0].playerIndex,valid[0].analysis,'ron',loserIndex);const entries=valid.map(v=>({scoreResult:v.analysis.scoreResult,context:v.analysis.context})),settlement=Sanma.Settlement.applyMultiRonSettlement({players:this.players,entries});if(!settlement.applied)return false;const result={type:'double_ron',winnerIndexes:valid.map(v=>v.playerIndex),winnerIndex:valid[0].playerIndex,isMultiRon:true,winType:'ron',fromPlayerIndex:loserIndex,winners:valid.map(v=>({winnerIndex:v.playerIndex,winType:'ron',score:v.analysis.scoreResult,yaku:v.analysis.yakuResult})),settlement};return this.endRound(result);},
runCpuUntilHumanTurn(){if(this.cpuTaskActive)return;this.cpuTaskActive=true;let guard=0;try{while(this.phase==='cpu-running'&&guard++<200){const p=this.players[this.turnIndex];if(!p||p.isHuman)break;if(!p.lastDraw){if(!this.drawFor(p))break;if(this.phase!=='cpu-running')break;}if(this.tryTsumo(p.id))break;const kita=Sanma.KitaManager.canExtract(this,p.id);if(kita.enabled&&kita.options.length&&this.wall.remainingCount()>0){const r=Sanma.KitaManager.extract(this,p.id,kita.options[0].instanceId);if(r.applied){this.recordGameEvent('kita',{playerIndex:p.id});if(this.tryTsumo(p.id))break;}}
        const kan=Sanma.KanRules.describeAvailability(this,p.id,this.ruleConfig);if(kan.enabled&&kan.options.length&&this.wall.remainingCount()>0&&this.cpuRandom()<0.15){if(this.applyKan(p.id,kan.options[0])){if(this.phase!=='cpu-running')break;continue;}}
        const riichi=Sanma.RiichiManager.canDeclare(this,p.id);if(riichi.enabled&&this.cpuRandom()<0.7){const rr=Sanma.RiichiManager.declare(this,p.id);if(rr.applied)this.recordGameEvent('riichi',{playerIndex:p.id});}
        const pending=p.riichi&&p.riichi.pending&&p.riichi.pendingDiscardInstanceIds&&p.riichi.pendingDiscardInstanceIds[0];const locked=p.hasRiichi&&p.lastDraw&&p.lastDraw.instanceId;const choice=pending?{tileInstanceId:pending,reason:'リーチ宣言牌'}:locked?{tileInstanceId:locked,reason:'リーチ後ツモ切り'}:Sanma.CpuStrategy.chooseDiscard({player:p,ruleConfig:this.ruleConfig,state:this,random:this.cpuRandom});const tile=choice&&p.discardTileByInstanceId(choice.tileInstanceId)||p.discardTileAt(p.hand.length-1);if(!tile)break;this.cpuThinkingLog.unshift({playerIndex:p.id,reason:choice&&choice.reason||''});this.cpuThinkingLog=this.cpuThinkingLog.slice(0,30);this.afterDiscard(p,tile);if(this.phase!=='cpu-running')break;}
      if(guard>=200){this.phase='round-ended';this.addLog('CPU進行ガードにより局を停止しました。');}
    }finally{this.cpuTaskActive=false;this.emitChange();}}
});
})(window);
